/**:
  ros__parameters:
    mass: 1.53
    trajectory_control:
      antiwindup_cte: 1.0
      alpha: 0.1
      kp:
        x: 2.0
        y: 2.0
        z: 2.0
      ki:
        x: 0.15
        y: 0.15
        z: 0.15
      kd:
        x: 1.065
        y: 1.065
        z: 1.065
      roll_control:
        kp: 1.85
      pitch_control:
        kp: 1.85
      yaw_control:
        kp: 2.85